version: "3"
services:
  random-number:
    image: vmmtt/random-number
    ports:
      - 8000:8000
    container_name: random-number
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower